language: c
sudo: required
dist: trusty
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - TESTS=false
        - EXTRA_REMOTES="git://github.com/Solo5/opam-solo5"
    matrix:
        - OCAML_VERSION=4.06
        - OCAML_VERSION=4.05
        - OCAML_VERSION=4.04
