language: c
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - TESTS=false PACKAGE=mirage-bootvar-solo5
    matrix:
        - OCAML_VERSION=4.09
        - OCAML_VERSION=4.08
        - OCAML_VERSION=4.07
